openapi: 3.0.1
info:
  title: API asociation
  version: 1.0.0
  description: API for memebership and activities of an asociation
servers:
  - url: 'https://api.example.com'
paths:
  /socios:
    get:
      summary: Devuelve lista de socios
      operationId: GetAllSocios
      description: Devuelve una lista de todos los socios miembros de la asociacion
      parameters:
        - in : query
          name: civilState
          description: Filtro por estado civil
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Socio'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      summary: subir un nuevo socio
      operationId: PostSocio
      responses:
        201:
          description: Recurso creado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Socio'
        400:
          description: bad request, nonsensical
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        409:
          description: Resource already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /socios/{id}:
    get:
      summary: Devuelve el ocio con el id indicado
      description: Busca el socio individual que tiene el id indicado
      responses:
        200 :
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Socio'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      summary: borrar socio cuyo DNI coincide con la búsqueda
      operationId: getSocioById
      responses:
        204:
          description: Borrado exitoso
        200:
          description: Borrado exitoso con confirmación
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Socio'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        409:
          description: Resource can’t be deleted due to dependencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      summary: editar socio cuyo DNI coincide con la búsqueda
      operationId: PutSocio
      responses:
        200:
          description: Update successful with response body
        204:
          description: Update successful without response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoContent'
        400:
          description: invalid update data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        404:
          description: Resource already gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        409:
          description: Update conflicts with the current state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /participantes:
    get:
      summary: Listar participantes
      parameters:
        - in: query
          name: socioId
          description: filtro por id de socio
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Lista de participantes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participante'
    post:
      summary: Crear participante (requiere socioId)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParticipanteCreate'
      responses:
        '201':
          description: Participante creado

  /participantes/{id}:
    get:
      summary: Obtener participante por ID
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participante'
    put:
      summary: Actualizar participante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParticipanteUpdate'
      responses:
        '200':
          description: Participante actualizado
    delete:
      summary: Baja lógica del participante

      responses:
        '204':
          description: Participante desactivado


  /actividades:
    get:
      summary: Listar actividades
      parameters:
        - in: query
          name: tipo
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actividad'
    post:
      summary: Crear actividad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActividadCreate'
      responses:
        '201':
          description: Actividad creada

  /servicios:
    get:
      summary: Listar servicios
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Servicio'
    post:
      summary: Crear servicio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServicioCreate'
      responses:
        '201':
          description: Servicio creado

  /inscripciones-actividad:
    post:
      summary: Inscribir participante en actividad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InscripcionActividadCreate'
      responses:
        '201':
          description: Inscripción creada

  /inscripciones-servicio:
    post:
      summary: Inscribir participante en servicio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InscripcionServicioCreate'
      responses:
        '201':
          description: Inscripción creada





components:
  schemas:
    Socio:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: identificador de socio
        dni:
          type: string
          pattern: '^[0-9]{8}[A-Z]$'
          description: dni de socio
        name:
          type: string
          description: nombre de socio
        surname:
          type: string
          description: apellidos de socio
        email:
          type: string
          format: email
          description: email de socio
        birthDate:
          type: string
          format: date
          description: fecha de nacimiento de socio
        address:
          type: string
          description: direccion de vivienda de socio
        phoneNumber:
          type: string
          pattern: '^+34 [0-9]{9}$'
          description: nº de telefono de socio
        civilState:
          type: string
          description: estado civil de socio
        isTutor:
          type: boolean
          description: socio es tutor o no
        entryDate:
          type: string
          format: date
          description: fecha de alta de socio

    SocioCreate:
      required: [dni, nombre, email]
      allOf:
        - $ref: '#/components/schemas/Socio'

    SocioUpdate:
      allOf:
        - $ref: '#/components/schemas/Socio'

    Participante:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: id de participante
        socioId:
          type: integer
          format: int32
          description: identificador de participante
        dni:
          type: string
          pattern: '^[0-9]{8}[A-Z]$'
          description: dni de participante
        name:
          type: string
          description: nombre de participante
        surname:
          description: apellido de participante
          type: string
        email:
          description: email de participante
          type: string
        birthDate:
          description: fecha de nacimiento de participante
          type: string
          format: date
        needs:
          description: necesidades especiales de participante
          type: string
        typeRel:
          description: tipo de relación del participante respecto a su socio

    ParticipanteCreate:
      required: [socioId, nombre]
      allOf:
        - $ref: '#/components/schemas/Participante'

    ParticipanteUpdate:
      allOf:
        - $ref: '#/components/schemas/Participante'

    Actividad:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        type:
          type: string
        price:
          type: number
        dateTime:
          type: string
          format: date-time
        location:
          $ref: '#/components/schemas/Location'

    ActividadCreate:
      allOf:
        - $ref: '#/components/schemas/Actividad'

    Servicio:
      type: object
      properties:
        id:
          type: integer
        price:
          type: number
        location:
          $ref: '#/components/schemas/Location'

    ServicioCreate:
      allOf:
        - $ref: '#/components/schemas/Servicio'

    Location:
      type: object
      properties:
        address:
          type: string
        latitude:
          type: number
        longitude:
          type: number

    InscripcionActividadCreate:
      required: [participanteId, actividadId]
      type: object
      properties:
        participanteId:
          type: integer
        actividadId:
          type: integer
        fechaReserva:
          type: string
          format: date


    InscripcionServicioCreate:
      required: [participanteId, servicioId]
      type: object
      properties:
        participanteId:
          type: integer
        servicioId:
          type: integer
        fechaReserva:
          type: string
          format: date


    NoContent:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 204
        message: No content
        title: no-content
    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 500
        message: Internal server error
        title: internal-server-error
    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 404
        message: Resource could not be found
        title: not-found
    BadRequest:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 400
        message: Bad quest
        title: bad-request
    Conflict:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 409
        message: conflicting events
        title: conflict
    ErrorResponse:
      type: object
      properties:
        code:
          type: number
          format: integer
          description: codigo de estado
        message:
          type: string
          description: mensaje de error
        title:
          type: string
          description: titulo
